/**
 * Оператор присваивания.
 * Что выведется в консоль?
 */

let c = 0;
const a = 5 + 7 + (c = 3 + 1);

console.log(a);


/**
 * Логические операторы.
 * Что выведется в консоль?
 */

console.log(true || false);
console.log(false || false);
console.log(false || false || true || false);
console.log(false || false || false || false);

console.log(false || null || 1 || undefined);
console.log(null || "kek" || false);
console.log(false || "0" || null);
console.log("" || null || undefined);


console.log(false && false);
console.log(true && false);
console.log(true && true);
console.log(true && true && false);

console.log("0" && 1 && "");
console.log(true && !null && null);
console.log(5 > 1 && 7 < 3 && undefined);

console.log(null ?? false ?? undefined);
console.log('kek' ?? 'lol' ?? null);
console.log(0 ?? false ?? null);
console.log(undefined ?? null ?? 42);
console.log(false ?? 0 ?? null ?? undefined);
console.log(null ?? undefined ?? "" ?? true);


/**
 * Ветвление.
 * Что будет выведено в консоль?
 */

if (true) {
  console.log('yes');
} else {
  console.log('no');
}

if (null || "") {
  console.log('yes');
} else {
  console.log('no');
}

if (4 % 2) {
  console.log('odd');
} else {
  console.log('even');
}

let username = "";
const autoGeneratedUserName = 'user591725'

if (!username) username = autoGeneratedUserName;
console.log(username);

// как переписать этот код через логический оператор?
// сработает ли оператор нулевого присваивания?


function add(number) {
  //...
}

const nullishNumber = 42 // или null, или undefined

// вызвать функцию только если внутри nullish number - число
